version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: karina
      POSTGRES_PASSWORD: karina
    volumes:
      - ./data:/var/lib/postgresql/data